notifications:
  email: false

sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull scottfleischman/agda:2.5.2

script:
  - docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.2 /bin/sh -c 'cd /opt/agda-build/Code; agda --allow-unsolved-metas Modular.agda'
  - docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.2 /bin/sh -c 'cd /opt/agda-build/Code; agda --allow-unsolved-metas Numbers.agda'
  - docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.2 /bin/sh -c 'cd /opt/agda-build/Code; agda --allow-unsolved-metas Presentation.agda'
  - docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.2 /bin/sh -c 'cd /opt/agda-build/Code; agda --allow-unsolved-metas Universe.agda'
  - docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.2 /bin/sh -c 'cd /opt/agda-build/Paper; agda --allow-unsolved-metas Everything.agda'
